export const LOG_IN = "LOG_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const REMOVE_PROFILE = "REMOVE_PROFILE";

export const HIDE_TOAST = "HIDE_TOAST";
export const SHOW_TOAST = "SHOW_TOAST";

export const SET_LOADING = "SET_LOADING";

export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";
export const DELETE_RESTAURANT = "DELETE_RESTAURANT";
export const SET_RESTAURANT_PARAMS = "SET_RESTAURANT_PARAMS";

export const GET_REVIEWS = "GET_REVIEWS";
export const ADD_REVIEW = "ADD_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const SET_REVIEW_PARAMS = "SET_REVIEW_PARAMS";

export const GET_USERS = "GET_USERS";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const SET_USER_PARAMS = "SET_USER_PARAMS";
